name: Deploy to EC2
on:
    push:
        branches:
            - cicd

env:
    AWS_REGION: eu-central-1
    CONTAINER_NAME: container

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [9.0.101]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
        
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{matrix.dotnet-version}}

            - name: Build project
              run: | 
                dotnet build -c Release
                echo "build successful"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with: 
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@master
              with:
                context: .
                push: true
                tags: saadns/dig:${{github.sha}}

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                 host: ${{env.HOSTNAME}}
                 key: ${{env.EC2_PRIVATE_KEY}}
                 username: ${{env.USER_NAME}}
                 scripts: |
                   docker stop dig || true
                   docker rm dig || true
                   docker pull ${{secrets.DOCKER_USERNAME}}/dig:${{github.sha}}
                   docker run -d --name dig 80:80 ${{secrets.DOCKER_USERNAME}}/dig:${{github.sha}}
              
