name: Deploy to EC2
on:
    push:
        branches:
            - master

env:
    AWS_REGION: eu-central-1
    CONTAINER_NAME: container

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [9.0.101]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
        
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{matrix.dotnet-version}}

            - name: Build project
              run: | 
                dotnet build -c Release
                echo "build successful"
    push:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            
            - name: Configure credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::149536456759:role/Dig-Role-Rq5NWekYxkWd
                aws-region: ${{env.AWS_REGION}}

            - name: Login to ECR repo
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag and push image to ecr
              env:
                REGISTRY: ${{steps.login-ecr.outputs.registry}}
                REPOSITORY: dig/dig
                IMAGE_TAG: ${{github.sha}}
              run: |-
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
